name: mssql2022-posh5

on: # push, pr, nightly, and on demand, for all branches 
  # push:
  #   branches-ignore:  # Prevents duplicate runs on PRs
  #     - release
  pull_request:  # Ensures PRs to main must pass the check
    branches:
      - release                      
  schedule:
    - cron: '0 3 * * *' 
  workflow_dispatch:
  workflow_call:  # This enables the workflow to be called from other workflows
jobs:
  run-autopilot-sql22-psh5:
    runs-on: windows-latest
    name: run-tdm-autopilot-sql22-psh5
    environment: 'build-posh5'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install rgclone CLI
        id: installCLI
        env:
          RGCLONE_API_ENDPOINT: ${{ secrets.RGCLONE_API_ENDPOINT }}
          RGCLONE_ACCESS_TOKEN: ${{ secrets.RGCLONE_ACCESS_TOKEN }}
        run: |
          # Download the rgclone CLI
          $downloadUrl = $env:RGCLONE_API_ENDPOINT + "cloning-api/download/cli/windows-amd64"
          $zipFile = ".\rgclone.zip"
          $rgCloneLocation = "."
          Write-Output "  Downloading rgclone.exe zip file..."
          Write-Output "    from: $downloadUrl"
          Write-Output "    to:   $zipFile"
          $ProgressPreference = 'SilentlyContinue'  # Disable slow progress updates
          Invoke-WebRequest -Uri $downloadUrl -OutFile "$zipFile" -UseBasicParsing
          Write-Output "  Extracting zip to: $rgCloneLocation"
          Add-Type -assembly "System.IO.Compression.Filesystem";
          [IO.Compression.Zipfile]::ExtractToDirectory($zipFile, $rgCloneLocation);
          
      - name: Create data image
        id: createIm
        env:
          RGCLONE_API_ENDPOINT: ${{ secrets.RGCLONE_API_ENDPOINT }}
          RGCLONE_ACCESS_TOKEN: ${{ secrets.RGCLONE_ACCESS_TOKEN }}
        run: |
          $emptyDiName = 'autopilot-sqlserver-2022-empty'
          $output = .\rgclone get di $emptyDiName --ignore-not-found -o json
          $imageStatus = ($output | ConvertFrom-Json).Status
          if ($output -eq $null -or $output -eq "") {
              Write-Output "Image does not exist. Creating image..."
              .\rgclone create di -f .\helper_scripts\empty-image-2022.yaml
          } 
          elseif ($imageStatus -like "Completed") {
              Write-Output "Image already exists. Moving on..."
          } 
          elseif ($imageStatus -like "Pending") {
              Write-Output "Image creation is Pending. Waiting until ready. (Image creation usually takes about 60 seconds)..."
              $stopwatch =  [system.diagnostics.stopwatch]::StartNew()
              while ($stopwatch.Elapsed.TotalSeconds -lt 315) {
                  Start-Sleep -Seconds 10
                  $output = .\rgclone get di $emptyDiName --ignore-not-found -o json
                  $imageStatus = ($output | ConvertFrom-Json).Status
                  $elapsedSeconds = $stopwatch.Elapsed.TotalSeconds
                  Write-Output "  ${elapsedSeconds} seconds: Image status is $imageStatus"

                  if ($imageStatus -like "Completed") {
                      $stopwatch.Stop()
                      break
                  }
                  elseif ($imageStatus -like "Create Failed") {
                      Write-Error "Image creation failed!"
                      $stopwatch.Stop()
                      break
                  }
                  elseif ($imageStatus -notlike "Pending") {
                      Write-Warning "  ${elapsedSeconds} seconds: Image state is neither "Completed", "Failed", nor "Pending". Something unexpected happened. Exiting."
                      $stopwatch.Stop()
                      break
                  }                  
                  if ($elapsedSeconds -ge 300) {
                      Write-Warning "  ${elapsedSeconds} seconds: Image creation is taking longer than expected. Crossing our fingers and moving on..."
                      $stopwatch.Stop()
                      break
                  }   
              }
          }
          else {
              Write-Warning "Image is in an unexpected state (neither "Completed", "Pending", nor NULL). Image status is: $imageStatus"
          }
                    
      - name: Create data container
        id: createDc
        env:
          RGCLONE_API_ENDPOINT: ${{ secrets.RGCLONE_API_ENDPOINT }}
          RGCLONE_ACCESS_TOKEN: ${{ secrets.RGCLONE_ACCESS_TOKEN }}
        run: |
          # Create an empty SQL Server instance on which to run autopilot
          Write-Output "Creating data container"
          $emptyDiName = 'autopilot-sqlserver-2022-empty'
          $output = .\rgclone create dc -i $emptyDiName -t 20m -o json | ConvertFrom-Json
          $dbPassword = $output.password
          $dbUser = $output.user
          $sqlhost = $output.host
          $sqlport = $output.port
          $instance = "${sqlhost},${sqlport}"
          Write-Output "Data container created successfully and available at: $instance"

          # Set output values so that I can use them in subsequent steps
          echo "::set-output name=dbUser::$dbUser"
          echo "::set-output name=dbPassword::$dbPassword"
          echo "::set-output name=instance::$instance"

      - name: Run Autopilot for TDM in PowerShell 5
        shell: powershell
        env:
          REDGATE_LICENSING_PERMIT: ${{ secrets.REDGATE_LICENSING_PERMIT  }}
        run: |
          Write-Output 'Running in PowerShell 5'
          $PSVersionTable
          $psVersion = $PSVersionTable.PSVersion.Major
          if ($psVersion -notlike "5"){
            Write-Error "PowerShell version should be 5, but it is $psVersion"
            exit 1
          }
          Write-Output 'Running Autopilot for TDM...'
          Write-Output '  -sqlInstance ${{ steps.createDc.outputs.instance }}'
          Write-Output '  -sqlUser ${{ steps.createDc.outputs.dbUser }}'
          .\run-tdm-autopilot.ps1 -sqlUser '${{ steps.createDc.outputs.dbUser }}' -sqlPassword '${{ steps.createDc.outputs.dbPassword }}' -sqlInstance '${{ steps.createDc.outputs.instance }}' -autoContinue -skipAuth -iAgreeToTheRedgateEula

      - name: Validating results
        shell: powershell
        if: ${{ always() }}
        run: |
          import-module dbatools
          Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true
          Set-DbatoolsConfig -FullName sql.connection.encrypt -Value $false
          $SqlCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList ${{ steps.createDc.outputs.dbUser }}, (ConvertTo-SecureString ${{ steps.createDc.outputs.dbPassword }} -AsPlainText -Force)
          
          # Validating rgsubset
          $totalOrders = (Invoke-DbaQuery -SqlInstance '${{ steps.createDc.outputs.instance }}' -Database AutopilotDev -Query "SELECT COUNT (*) AS TotalOrders FROM Sales.Orders" -SqlCredential $SqlCredential).TotalOrders
          Write-Output "If rgsubset ran successfully, there should be 499 orders in the AutopilotDev database"
          Write-Output "Total Orders: $totalOrders"
          if ($totalOrders -eq 498) {
            Write-Output "rgsubset ran successfully"
          } else {
            Write-Error "rgsubset did not run successfully"
            exit 1
          }

          # Validating rganonymize
          $customer570Address = (Invoke-DbaQuery -SqlInstance '${{ steps.createDc.outputs.instance }}' -Database AutopilotDev -Query "SELECT Address FROM Customers.Customer WHERE CustomerID = 570" -SqlCredential $SqlCredential).Address
          Write-Output "If rganonymize ran successfully, Customer 570 should NOT be 55 Maromas St."
          Write-Output "Address: $customer570Address"
          if ($customer570Address -like "55 Maromas St.") {
            Write-Error "rganonymize did not run successfully"
            exit 1
          } else {
            Write-Output "rganonymize ran successfully"
          }
